### ISSUE TITLE
how to send images?

### ISSUE THREAD

**Issue by horapusa-lk** [robvanderleek/mudslide#1]
can i send whatsapp messages with image using this script?.If not availerble I hope you add this feature

**Comment by CH1NRU5T** [comment]
+1

**Comment by robvanderleek** [comment]
Hi @horapusa-lk @CH1NRU5T 👋 

I've added commands to send images to individuals or groups, for example:

```
npx mudslide@latest send-image me image.png
```

Also see the [Readme](https://github.com/robvanderleek/mudslide#sending-an-image-file).

Let me know if you bump into any issues, thanks for the feedback!

**Comment by CH1NRU5T** [comment]
By any chance, can you add the command to share files? .apk etc.? 
Thank you for mentioning it by the way.

**Comment by robvanderleek** [comment]
Hi @CH1NRU5T 

The Mudslide tool only implements a small subset of everything that can be done through the WhatsApp API (this is a side project and my time is very limited).

If you want this feature, please [create a new issue](https://github.com/robvanderleek/mudslide/issues/new), briefly describe your use-case and I'll attach a label to the issue so others can "upvote" it with likes. If there's enough interest I'll add the feature 🙂 

KR, Rob
