### ISSUE TITLE
Feature request: add caption text to send-image command 

### ISSUE THREAD

**Issue by lightaffaire** [robvanderleek/mudslide#10]
1. very usefull script. Thanks.

2. would be great if one could add a caption text when posting images ie.

$ npx mudslide send-image me /tmp/test.jpg 'caption text to image'
or 
$ npx mudslide send-image me /tmp/test.jpg send-image-text 'caption text to image'

otherwise loving it!

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

There was already an option for that, but undocumented. I've [updated the Readme](https://github.com/robvanderleek/mudslide#image-captions).

Thanks for the feedback!
