### ISSUE TITLE
Reading Messages  FROM WHATSAPP +GROUPS

### ISSUE THREAD

**Issue by Anayaali2019** [robvanderleek/mudslide#100]
AS Baileys NOW SUPPORT Reading Message please update mudslide as well

https://github.com/WhiskeySockets/Baileys?tab=readme-ov-file#reading-messages

**Comment by robvanderleek** [comment]
The goal of Mudslide is to make sending messages from the command-line easy, please use the Baileys library directly (or another tool) if you want to read messages.
