### ISSUE TITLE
QR code not generated

### ISSUE THREAD

**Issue by SureshVeeraRaghavan** [robvanderleek/mudslide#109]
Dear rob, with the latest release the None of the existing config worked.Also when I tried for a new login teh QR code is not displayed. Guide me on how to proceed

**Comment by gijsyo** [comment]
Same here. QR code isn't showing. Logging out works fine, but logging back in doesn't. Going back a version doesn't seem to make a difference.

Verbose log (it keeps cycling so I ^C'ed out of it)

```
npx mudslide login -vvv
ℹ  info      In the WhatsApp mobile app go to "Settings > Connected Devices > 
ℹ  info      Connect Device" and scan the QR code below
{"level":30,"time":1724425637909,"pid":57431,"hostname":"chrysanthemum.local","browser":["macOS","Chrome","10.15.0"],"helloMsg":{"clientHello":{"ephemeral":"Z8a70a2e0Ll9d29fbXDtZ7EPnnSIXC4qhtYMME4vnGQ="}},"msg":"connected to WA"}
{"level":10,"time":1724425637936,"pid":57431,"hostname":"chrysanthemum.local","class":"ns","msg":"recv 350 bytes, total recv 350 bytes"}
{"level":10,"time":1724425637936,"pid":57431,"hostname":"chrysanthemum.local","class":"ns","msg":"recv frame"}
{"level":10,"time":1724425637937,"pid":57431,"hostname":"chrysanthemum.local","handshake":{"serverHello":{"ephemeral":"r2MQQWK4MQ8RQRmFsX5RL96Ac3zZD4VIYwqa34WgsRs=","static":"0WzMLj8WZfJpfBWknTRyEsvpR//GV8PSF9Qt7RrNDP+8o148+kJYIzLruJtAQzHp","payload":"oLAUc47RuWA8fJ2z92UKXmw70sduCfEFzjcu2kwssdgbLT9DJOgxMZhx4LFft4cG4SxSmejz54Q9myuIYkn7TTFwqTGm3IoPv2HXTLftL5wZfK+WPEI/5MffqPNrJWLVLtqC3rxRvuU2zS1GT8mq/yGKlx7jXYdcAQtc43EdHFr9C+/7CT4VSnghjGj8lAggM/yZKwACD5O6SKE900SpkDNFiSBKQj+6ZwgZAZDCQHQzzO1Avzkg982zTK2Cbwr7YhnaNQ1vF9f6JSYIzGYaKNE7oFWMp1xEXGpeuJGGwyIAZxs5hkLj84wVix0f9msUwML6y1OqVtOAz+DuO065uPc="}},"msg":"handshake recv from WA"}
{"level":30,"time":1724425637942,"pid":57431,"hostname":"chrysanthemum.local","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":1},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAArw==","eKeytype":"BQ==","eIdent":"C0SKBlDIHnhdSYJcgrTsxMpp2RWzLtb3uxXC3Mrn4Q0=","eSkeyId":"AAAB","eSkeyVal":"DuGdCKmCNFgxTp9Qjmn2X1/UUFuqSz63mFiwbfY5FSQ=","eSkeySig":"EsInx0MQ0Vwb7nfftvfmtJemBB4qGBaAdmMVuTtMViEnxQ8C1xZy828dgr7Ih3vKvm7KiJSCujMQjwA3oBG0hQ==","buildHash":"J56Tkvzsr6X+KBUF6gZ+8w==","deviceProps":"CgVtYWNPUxgBIAA="}},"msg":"not logged in, attempting registration..."}
^C

```

**Comment by SureshVeeraRaghavan** [comment]
the verbose mode of login command shows these errors.
npx mudslide@latest -v login
ℹ  info      In the WhatsApp mobile app go to "Settings > Connected Devices > 
ℹ  info      Connect Device" and scan the QR code below
{"level":30,"time":1724435220381,"pid":47580,"hostname":"Sureshs-MacBook-Air.local","browser":["macOS","Chrome","10.15.0"],"helloMsg":{"clientHello":{"ephemeral":"Jv6DA0+1qC58Cz1JEesKt5sZFChyPSYzYI2Yha3pxDw="}},"msg":"connected to WA"}
{"level":30,"time":1724435220619,"pid":47580,"hostname":"Sureshs-MacBook-Air.local","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":1},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAA9A==","eKeytype":"BQ==","eIdent":"TbvGzf237YtY2iQrikiHJUJyUDgJImXOghQRt+MiVVU=","eSkeyId":"AAAB","eSkeyVal":"ssdsAeJhpRi6FnwG5E9XxTIMk5XK6L+nT7dn2XHp7lY=","eSkeySig":"JyjmBavAWk4HvgLWWVWNiJyQdluHY5nyFmTWbuyDgd4N8pcLLnGOYCW5sc2p8DvcpmGJU7IDV8nUbS7id3gQjA==","buildHash":"J56Tkvzsr6X+KBUF6gZ+8w==","deviceProps":"CgVtYWNPUxgBIAA="}},"msg":"not logged in, attempting registration..."}
{"level":30,"time":1724435223509,"pid":47580,"hostname":"Sureshs-MacBook-Air.local","trace":"Error: Connection Failure\n    at WebSocketClient.<anonymous> (/Users/sureshveeraraghavan/.npm/_npx/ce95761724e6020f/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:529:13)\n    at WebSocketClient.emit (node:events:519:28)\n    at WebSocketClient.emit (node:domain:488:12)\n    at /Users/sureshveeraraghavan/.npm/_npx/ce95761724e6020f/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:241:35\n    at Object.decodeFrame (/Users/sureshveeraraghavan/.npm/_npx/ce95761724e6020f/node_modules/@whiskeysockets/baileys/lib/Utils/noise-handler.js:149:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","msg":"connection errored"}
{"level":30,"time":1724435223890,"pid":47580,"hostname":"Sureshs-MacBook-Air.local","browser":["macOS","Chrome","10.15.0"],"helloMsg":{"clientHello":{"ephemeral":"dwtqLzmHZw2dnSO2vhYXwvrRedHJzrw2Nn+Bj1BVXCY="}},"msg":"connected to WA"}
{"level":30,"time":1724435224149,"pid":47580,"hostname":"Sureshs-MacBook-Air.local","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":1},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAlA==","eKeytype":"BQ==","eIdent":"uBK3WycXBEg1IMC3RjzfvWS+JrStHqmghSHL4aOYFh4=","eSkeyId":"AAAB","eSkeyVal":"xe14ckAK+sQeL6Pik6FDgXJzIv++FYUPVck9FezDvAw=","eSkeySig":"dqJklW6conRFYr9Y7IsKzErK77Ph36jxpyK7QnPwPW+R7n0CDdXQxEfQQBaZpLRYMKFuqwHU8/n5XlSMaxymhw==","buildHash":"J56Tkvzsr6X+KBUF6gZ+8w==","deviceProps":"CgVtYWNPUxgBIAA="}},"msg":"not logged in, attempting registration..."}

**Comment by MorganBlack** [comment]
Hi,
I can confirm that I've been experiencing the same issue since around 8 pm GMT yesterday.

`i  info      In the WhatsApp mobile app go to "Settings > Connected Devices > 
i  info      Connect Device" and scan the QR code below
{"level":30,"time":1724435173004,"pid":14364,"hostname":"HOST","browser":["Windows","Chrome","10.15.0"],"helloMsg":{"clientHello":{"ephemeral":"cmTS9z8sQV9Luo60WJf+F9S8FkXumWEitAv3Sa655Tw="}},"msg":"connected to WA"}
{"level":10,"time":1724435173092,"pid":14364,"hostname":"HOST","class":"ns","msg":"recv 350 bytes, total recv 350 bytes"}
{"level":10,"time":1724435173092,"pid":14364,"hostname":"HOST","class":"ns","msg":"recv frame"}
{"level":10,"time":1724435173093,"pid":14364,"hostname":"HOST","handshake":{"serverHello":{"ephemeral":"Ibibq5zoejTU/T6CVQqNL/Psq+RcCG7Gl7IHMC4f4Hw=","static":"tvX/orariJLP0YMyOJ4Qc8/569/Yd0apdWEqSV0vxuJZC/91XnZVUML6RsAAOxp5","payload":"WD1Y9KQ1T8vb8tgFV8AeL2iGuO6i4Cycngh8Ujb4iq42z4zPGVxCrgVegOHFyVaFbcgefre9qm69xOOAkmJl8Um0dImTOYSyZa+yLJpAAoRufUII4usdBwqRcG8LhpNFnuZjZ6TDbykJUpSscQH11OW6VYOEBVzqhffJQrIZRmTPToLH01J4tr2hITBfqzxHZ9UMxE7oBTDhVllmwFvNSXbbSIsOcNbOSn0AhrIRYZRIlicZIunb0eh4mwCQwyTcir0s1dMw3B4sPbJb5Wmixgprl3PQdK94RBJnXXxxn8vt5WiUX3wZp+9P4f3yaRN4JvK0Hi4rUZ6npDjqyCdpOow="}},"msg":"handshake recv from WA"}
{"level":30,"time":1724435173097,"pid":14364,"hostname":"HOST","node":{"passive":false,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2413,"tertiary":1},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","devicePairingData":{"eRegid":"AAAAdw==","eKeytype":"BQ==","eIdent":"tJtFlIzGjJAhZox8iqX6PNnNz4KKCOhhSOxXGPPRFnM=","eSkeyId":"AAAB","eSkeyVal":"pCc+Q366F9QXH7NzkA7HiUs4Si2FLeEQmDe/pcMMHHI=","eSkeySig":"bpTg0Z9/+6VeGhs/BQ8H/S28v+lAqtUYR6QAIoZQN/VhH8tAg5m8WHt6J5EccMW+oCXhYDSEe93FpoTMfM8ugw==","buildHash":"J56Tkvzsr6X+KBUF6gZ+8w==","deviceProps":"CgdXaW5kb3dzGAEgAA=="}},"msg":"not logged in, attempting registration..."}
{"level":10,"time":1724435174982,"pid":14364,"hostname":"HOST","class":"ns","msg":"recv 41 bytes, total recv 41 bytes"}
{"level":10,"time":1724435174983,"pid":14364,"hostname":"HOST","class":"ns","msg":"recv frame"}
{"level":10,"time":1724435174983,"pid":14364,"hostname":"HOST","xml":"<failure reason='405' location='frc'/>","msg":"recv xml"}
{"level":30,"time":1724435174984,"pid":14364,"hostname":"HOST","trace":"Error: Connection Failure\n    at WebSocketClient.<anonymous> (C:\\snapshot\\dist-ncc\\index.js)\n    at WebSocketClient.emit (node:events:527:28)\n    at WebSocketClient.emit (node:domain:475:12)\n    at C:\\snapshot\\dist-ncc\\index.js\n    at Object.decodeFrame (C:\\snapshot\\dist-ncc\\index.js)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","msg":"connection errored"}`

**Comment by Selnewehy** [comment]
I am experiencing same issue as well with both old and new version

**Comment by robvanderleek** [comment]
Hi all,

Please try the latest version (0.29.1) to see if it fixes your login issues.

Also, please remember: do not rely on Mudslide for important things, as it uses an official API (through the Baileys library) that is fragile and can break without notice.

**Comment by MorganBlack** [comment]
When running 0.29.1 I get:

```
ℹ  info      In the WhatsApp mobile app go to "Settings > Connected Devices >
ℹ  info      Connect Device" and scan the QR code below
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^
Error: Cannot find module './718.index.js'
Require stack:
- /snapshot/dist-ncc/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a
 literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it
from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.require (/snapshot/dist-ncc/index.js)
    at /snapshot/dist-ncc/index.js
    at Array.reduce (<anonymous>)
    at Function.e (/snapshot/dist-ncc/index.js) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/snapshot/dist-ncc/index.js' ],
  pkg: true
}
```

**Comment by Fabriciovms** [comment]
I restored the npx file in /usr/bin from a backup made yesterday at 10:00 PM and successfully generated the QR code.

**Comment by DurvalPaicheco** [comment]
Working ! 

> Hi all,
> 
> Please try the latest version (0.29.1) to see if it fixes your login issues.
> 
> Also, please remember: do not rely on Mudslide for important things, as it uses an official API (through the Baileys library) that is fragile and can break without notice.

**Comment by gijsyo** [comment]
> Hi all,
> 
> Please try the latest version (0.29.1) to see if it fixes your login issues.
> 
> Also, please remember: do not rely on Mudslide for important things, as it uses an official API (through the Baileys library) that is fragile and can break without notice.

Works for me!

**Comment by robvanderleek** [comment]
> When running 0.29.1 I get:
> 
> ```
> ℹ  info      In the WhatsApp mobile app go to "Settings > Connected Devices >
> ℹ  info      Connect Device" and scan the QR code below
> node:internal/modules/cjs/loader:933
>   const err = new Error(message);
>               ^
> Error: Cannot find module './718.index.js'
> Require stack:
> - /snapshot/dist-ncc/index.js
> 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a
>  literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it
> from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at Module.require (pkg/prelude/bootstrap.js:1851:31)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.require (/snapshot/dist-ncc/index.js)
>     at /snapshot/dist-ncc/index.js
>     at Array.reduce (<anonymous>)
>     at Function.e (/snapshot/dist-ncc/index.js) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/snapshot/dist-ncc/index.js' ],
>   pkg: true
> }
> ```

Please follow https://github.com/robvanderleek/mudslide/issues/56 for this issue.

**Comment by yuwandaIndraGunawan** [comment]
> I restored the npx file in /usr/bin from a backup made yesterday at 10:00 PM and successfully generated the QR code.

Is npx automatically backed up? Or can I ask your backup?

**Comment by MorganBlack** [comment]
> > When running 0.29.1 I get:
> > ```
> > ℹ  info      In the WhatsApp mobile app go to "Settings > Connected Devices >
> > ℹ  info      Connect Device" and scan the QR code below
> > node:internal/modules/cjs/loader:933
> >   const err = new Error(message);
> >               ^
> > Error: Cannot find module './718.index.js'
> > Require stack:
> > - /snapshot/dist-ncc/index.js
> > 1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a
> >  literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it
> > from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
> >     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
> >     at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
> >     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
> >     at Module.require (node:internal/modules/cjs/loader:1005:19)
> >     at Module.require (pkg/prelude/bootstrap.js:1851:31)
> >     at require (node:internal/modules/cjs/helpers:102:18)
> >     at Object.require (/snapshot/dist-ncc/index.js)
> >     at /snapshot/dist-ncc/index.js
> >     at Array.reduce (<anonymous>)
> >     at Function.e (/snapshot/dist-ncc/index.js) {
> >   code: 'MODULE_NOT_FOUND',
> >   requireStack: [ '/snapshot/dist-ncc/index.js' ],
> >   pkg: true
> > }
> > ```
> 
> Please follow #56 for this issue.

That did the trick. Thank you.

**Comment by SureshVeeraRaghavan** [comment]
Works for me too. Though Rob says always not to run big projects in it, I find wherever I add this it becomes a bigger project. Thanks Rob
