### ISSUE TITLE
Feature request: npx mudslide users

### ISSUE THREAD

**Issue by lightaffaire** [robvanderleek/mudslide#11]
Add 'mudslide users' to either:

1. list all single phone users from address book

or

2. list all single phone users currently in WA chat window/screen  { "id": "number", "name": "users name in WA"}

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

The library Mudslide is based on unfortunately [does not provide](https://github.com/adiwajshing/Baileys/issues/2210) a simple "get all contacts" functionality (it does provide that for groups).
