### ISSUE TITLE
Error: Cannot find module '/app/dist/index.js' when using Docker image

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [robvanderleek/mudslide#112]
Hi,

I have attempted to run the current Docker image and am receiving errors.  Details are:

Container version:
`[robvanderleek/mudslide@sha256:7c3dcb705b0ee587c80f83771353688c78276efb300e482c06b49637f895d479]` (ie 0.29.2 which is the latest release)

Command is as suggested in README:
`docker run -v /appdata/mudslide:/usr/src/app/cache -it robvanderleek/mudslide login`

Error:
```
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module '/app/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.17.
```

Can you please suggest how to proceed?

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
In experimentation, it looks like `yarn` is building the app in /app/build instead of /app/dist.  Updating the Dockerfile to:

`ENTRYPOINT ["node", "./build/index.js"]`

Fixes the issue.

**Comment by robvanderleek** [comment]
Hi @ThisIsTheOnlyUsernameAvailable 

You are right, this broke recently. Thanks for reporting and for locating the root-cause.
I've fixed the path.

KR, Rob
