### ISSUE TITLE
Feature Request: URL preview

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [robvanderleek/mudslide#113]
Fantastic app.  Thanks for your work on it.

I have a feature request that I think would be valuable for a broad audience.  It'd be really nice to include URL previews if a message contains a link. Currently links sent from Mudslide are just the raw text:
<img src="https://github.com/user-attachments/assets/1880703b-04f5-4e30-879e-0a02766a0b70" width=50% height=50%>

However if you paste a link in the native WhatsApp client, it'll generate a preview:
<img src="https://github.com/user-attachments/assets/95667fe1-660b-4594-8e7f-a7f7ebe473d9" width=50% height=50%>
I believe Baileys has the [capability](https://baileys.whiskeysockets.io/functions/generateLinkPreviewIfRequired.html) to include the preview.

Is this something that can be included?

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Thanks very much, @robvanderleek!  I will test in the coming couple of days.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Thanks again for your work on including this functionality, @robvanderleek .  I've now had a chance to test and have some feedback.  I'm ignoring the imdb issue as it seems like it's the only URL that isn't working for me, so I'm assuming it's site-specific.

It seems that the preview parses the site heading, but does not include the image rendering.  For example, the following shows the same link sent from the native WA client, and then from Mudslide:

![good-bad](https://github.com/user-attachments/assets/768d47be-bcd4-40cf-ba31-374602267dd8)

The above is the same for other sites too:

![Native](https://github.com/user-attachments/assets/3dc9f143-a165-42d1-958a-81d98edbfc75)
versus
![mudslide2](https://github.com/user-attachments/assets/669a9792-62d2-44b8-b8a3-6240a9ed7fa5)


I've seen a [ticket](https://github.com/WhiskeySockets/Baileys/issues/260) talking about image sizing for the preview so understand that an image should be generated.

Do you see the same?

**Comment by robvanderleek** [comment]
Hi @ThisIsTheOnlyUsernameAvailable 

I've added some [extra code](https://github.com/WhiskeySockets/Baileys/issues/260#issuecomment-1646746226) from the issue you mentioned, can you try again?

For me, on iOS WA client, the images do render (both with and without the extra code mentioned above):
![Schermafbeelding 2024-09-17 om 09 27 58 jpeg](https://github.com/user-attachments/assets/1a95d2c4-e80d-4e8f-92ae-1e8619425c8c)

What platform is your client running on?

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
I'm using Android and am not seeing the previews.  However it looks like this is a known bug: https://github.com/WhiskeySockets/Baileys/issues/347

Thanks for your implementation of the feature; I really appreciate it.  I'll see if I can get it fixed upstream.
