### ISSUE TITLE
Button support documentation

### ISSUE THREAD

**Issue by fpoonja** [robvanderleek/mudslide#124]
@robvanderleek - It looks like you added button support based on this previous ticket, but I don't see the information in the ReadMe or the link in the branch? - Can you confirm if thesis still supported and what the documentation is.

Previous Ticket: https://github.com/robvanderleek/mudslide/issues/21

Cheers,

**Comment by fpoonja** [comment]
[found another ticket that explains this has been removed](https://github.com/robvanderleek/mudslide/issues/65)

**Comment by robvanderleek** [comment]
Hi @fpoonja 

As a short follow-up on your question: Button support was explicitly dropped from Baileys (the library I'm using), [see this issue](https://github.com/WhiskeySockets/Baileys/pull/956) for a bit of background on why it was dropped.
