### ISSUE TITLE
mudslide-linuxstatic-arm64 crashing on Raspberry Pi OS bookworm

### ISSUE THREAD

**Issue by MorganBlack** [robvanderleek/mudslide#125]
Hi, 

I've been unable to use any of the 0.29.X versions of ./mudslide-linuxstatic-arm64

All I get is:

```
./mudslide-linuxstatic-arm64
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/snapshot/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.11.1
```

Thank you,
Morgan

**Comment by robvanderleek** [comment]
Hi @MorganBlack 

Building the ARM64 static binary is indeed failing in the release workflow. I did not notice this, thanks for reporting.

There seems to be an issue with building Linux ARM64 binaries on Linux x86, I've filled a bug report for that [here](https://github.com/yao-pkg/pkg/issues/95).

BTW I was able to generate an ARM64 binary for Linux on macOS, so as a workaround for the time being, you might want to try generating the binary by hand on a different platform.

**Comment by robvanderleek** [comment]
Hi @nerdseverino (@MorganBlack)

Building the ARM64 binaries on a Linux GHA runner is still broken, but I've switched to a macOS runner for now and that looks better.

Can you try the ARM64 binary of the latest release? https://github.com/robvanderleek/mudslide/releases/tag/0.30.2

**Comment by robvanderleek** [comment]
Thanks for the detailed check @nerdseverino
