### ISSUE TITLE
Feature Request:List Group Participants

### ISSUE THREAD

**Issue by pharmankur** [robvanderleek/mudslide#137]
Presently in Mudslide, groups functionality is limited to Listing ALL the groups names with group IDs or ADD/Remove participants in a listed group.

But, if we want to LIST the PARTICIPANTS in either a specified group or ALL PARTICIPANTS in ALL groups, there is presently no option available.

Can "**LIST PARTICIPANTS in a group**" functionality be added to mudslide ?

baileys.whiskeysockets.io has following documentation
[ I dont know if that is useful in adding up the required functionality in mudslide ] --> 
 
https://baileys.whiskeysockets.io/types/GroupMetadataParticipants.html
https://baileys.whiskeysockets.io/types/GroupParticipant.html
https://github.com/WhiskeySockets/Baileys/blob/34cfa92/src/Types/Message.ts#L198

**Comment by robvanderleek** [comment]
Hi @pharmankur 

I've added a [`list-group` command](https://github.com/robvanderleek/mudslide?tab=readme-ov-file#list-group-participants).

Thanks for the suggestion and checking the Baileys library for feasibility 👍
