### ISSUE TITLE
Automatic Login after Linux Server reboot

### ISSUE THREAD

**Issue by pthoelken** [robvanderleek/mudslide#147]
Hey Buddy, 

I'm planning to use your binary for sending my zabbix monitoring alerts to my WhatsApp phone number.  So far, so good. It works like charm but after a reboot of my linux server the mudslide told me, that mudslide is logged out.

In this case I have to login manually again after every server reboot. This is not an option. 

Is there a way to make the login persistent - also after a reboot?

**Comment by robvanderleek** [comment]
Hi @pthoelken 

WA credentials are [stored on disk in a cache folder](https://github.com/robvanderleek/mudslide?tab=readme-ov-file#configuration). As long as this folder is persisted over reboots you should stay logged in.

You can check the cache folder location using:

```shell
npx mudslide@latest me
```
