### ISSUE TITLE
How to add user to group!

### ISSUE THREAD

**Issue by horapusa-lk** [robvanderleek/mudslide#15]
Im kindly requesting you to add the user add to group feature to this tool.

**Comment by robvanderleek** [comment]
Hi @horapusa-lk 

Thanks for the feedback.

I've implemented basic functionality for adding and removing users from groups, please [see the Readme](https://github.com/robvanderleek/mudslide#addremove-group-participants).
Let me know if things don't work as expected.

KR, Rob

**Comment by horapusa-lk** [comment]
thanks. appriciate about you man.❤️
