### ISSUE TITLE
Send group invite if number is not in address book

### ISSUE THREAD

**Issue by eliafino** [robvanderleek/mudslide#161]
Currently, if a number that is not in the address book is invited to a group, the addition is notified but nothing happens.
From the official client, it asks if you want to invite via invitation, is it possible to do the same thing?

**Comment by robvanderleek** [comment]
Hi @eliafino 

Mudslide does not keep track of the user's address book, it's a fairly stateless tool.
I'm using the function [groupParticipantsUpdate](https://baileys.whiskeysockets.io/functions/makeWASocket.html#makeWASocket.__type.groupParticipantsUpdate) from the Baileys library. That function does return a result object which may indicate if the update was successful or not, so I've added a bit of logging that shows the status code after adding a user to a group, this will be included in the next release.

**Comment by eliafino** [comment]
Thank you very much @robvanderleek
