### ISSUE TITLE
buglet... remove the space -c help text 

### ISSUE THREAD

**Issue by lightaffaire** [robvanderleek/mudslide#17]
a buglet... remove the space at end of (default: path ) text. ie.

 -c, --cache <folder>                                   Override default cache folder (default: /root/.local/share/mudslide )

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

Thanks for the feedback.

In the latest version of Mudslide the default cache folder has moved from the help text to the `me` command.

KR, Rob
