### ISSUE TITLE
npx mudslide@latest login - no longer works

### ISSUE THREAD

**Issue by lightaffaire** [robvanderleek/mudslide#18]
UPDATE: after deleting /root/.local/share/mudslide  login  worked again. Was it something todo with the upgrade to 0.12?  Maybe add a --delete-cache option?

1. upgraded to 0.12

2. wanted to login so entered  $ npx mudslide login

after approx. 5 seconds the prompt returns but no QR code is displayed

tried a 

$ npx mudslide logout

and then again

$ npx mudslide login

same response... ~5 secs and shell prompt returns... no info messages from mudslide at all

could we get some more detailed info/flow via a --debug option?

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

I've also experienced this behavior, unfortunately, I haven't figured out yet what the issue with the `login` command is.

Logging out solves the login issue but that indeed can also fail to clear the cache properly.
I've improved the `logout` command so it tries harder to clear the cache.

Thanks for the feedback.
