### ISSUE TITLE
Run behind the Proxy

### ISSUE THREAD

**Issue by rdnkrkmz** [robvanderleek/mudslide#20]
Is it possible to run behind the corporate proxy.
Currently, when run while proxy set, no output given to console.

**Comment by robvanderleek** [comment]
Hi @rdnkrkmz 

I don't have any experience with Node apps and proxy servers.
There seems to be [a library](https://github.com/gajus/global-agent) that would make it quite easy to add proxy support though.

Can you tell me a bit more about your environment and use case? For example, do you have `HTTP_PROXY` and `HTTPS_PROXY` environment variables set? Do you need authentication for your proxy?

KR, Rob

**Comment by rdnkrkmz** [comment]
Hi  @robvanderleek 
First, thank you for your attention.

I have the following config:
on command prompt I set proxy as follows: before I set, I could not reach www.google.com.tr
```
set https_proxy=http://USER:PASS@proxy.server.com.tr:80
set http_proxy=http://USER:PASS@proxy.server.com.tr:80
```

when I try with `curl`, I can reach www.google.com.tr

Then I try to login with windows app as follows, but app just waits, netiher output nor etc on the console.

`D:\mudslide-win-x64.exe login`

**Comment by rdnkrkmz** [comment]
@robvanderleek 
Thank you for your efforts.
It works like a charm...
