### ISSUE TITLE
new feature Button selection

### ISSUE THREAD

**Issue by harut420** [robvanderleek/mudslide#21]
it would be very useful to have the ability to send out choice and user interaction buttons.

**Comment by robvanderleek** [comment]
Hi @harut420 

Thanks for the feedback.

Can you give an example (a screenshot would be nice) of the type of button messages you would like to send?
WhatsApp has different types and the underlying library I'm using only supports a few. 
Also, Mudslide is a command-line tool so it should be easy to configure the buttons/choices using command-line arguments/options.

KR, Rob

**Comment by harut420** [comment]
Hi @robvanderleek 
Thanks for your work first and fast response !!!

I attach a image to show you what i mean exactly, it is called quickmessage if i'm correct.

![image](https://user-images.githubusercontent.com/49169029/223999146-2c7b604c-32a2-4488-a482-413f4b3040df.png)

thanks!

**Comment by robvanderleek** [comment]
Hi @harut420 👋 

I've added basic support to include buttons in messages, please [see the Readme](https://github.com/robvanderleek/mudslide#buttons).
I'm not sure if this is the exact thing you included in the issue (somehow the quick-reply buttons from the library did not work for me), let me know if it suits your use case.

KR, Rob

**Comment by chhajervikram** [comment]
Hello robvanderleek 
Thanks For this USe Full Programme  , their is one issue while sending *.pdf  file  , is that if *.pdf files is on E:\tmp\P M GROUP\2223\PM IMPEX\2223\Invoice\abc.pdf , it do not support and inable t send . please rectifi this error .
 thank You 
 Vikram

**Comment by chhajervikram** [comment]
how to Update Mudslide  if new version is available 
Thanks
VIkram Chhajer

**Comment by robvanderleek** [comment]
Hi @chhajervikram 👋 

Your questions are not related to this issue, can you please create a new issue? 🙂 
If you create an issue for the PDF files, can you let me know what the exact error is?

If you run Mudslide using `npx` appending `latest` will always check for the latest version:
```shell
npx mudslide@latest -V
```

Kind regards, Rob
