### ISSUE TITLE
Add the ability to change the label that whatsapp app sees in linked devices

### ISSUE THREAD

**Issue by lightaffaire** [robvanderleek/mudslide#23]
When I look at the linked devices to my whatsapp account I see something like:

Chrome(Windows)
Firefox(Linux)
Chrome(Baileys)

It would be useful and probably prudent to allow mudslide to register itself as:

  Firefox|Chrome (Windows | Linux)

Whatsapp/Meta could easily block anything with Baileys on the linked device string so conform to whats usually visable.

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

Thanks for the feedback.

I've updated the connection string, Mudslide now registers itself as `Google Chrome (<OS>)`, for example: `Google Chrome (macOS)`.

You are right, it's probably safer this way. However, note that Mudslide is based on an unofficial WhatsApp library so long-term access is unfortunately unguaranteed.

KR, Rob
