### ISSUE TITLE
bug on 0.15: --footer not working

### ISSUE THREAD

**Issue by lightaffaire** [robvanderleek/mudslide#26]
$ npx mudslide@latest send me 'hello\nworld' --footer 'bye!'

on my 0.15 install only this appears on my WA:

hello
world

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

The command `npx mudslide@latest send me 'hello\nworld' --footer 'bye!'` shows on my iOS app:

![IMG_3052](https://user-images.githubusercontent.com/5324924/224480500-859a342b-023b-4b6d-95e6-103198efa5f6.jpg)

However, in the web app I see:

<img width="135" alt="image" src="https://user-images.githubusercontent.com/5324924/224480526-fe1d1401-f328-4a62-b84e-1409c03682b3.png">

Could it be a limitation of the web app? Could you check how it looks on a mobile app?

**Comment by lightaffaire** [comment]
I have upgraded to 0.16 and have noticed this:

1. from fedora 37 linux to WA web I get:

hello
world

but no --footer text (bye!)

2. checking the same user on my android pixel 7 pro WA app I see NOTHING... no text and no footer!

send me / send-file me --caption / send-image me --caption ALL WORK OK and are visible on WA android app

**Comment by robvanderleek** [comment]
Sorry to hear it doesn't work for you.

```shell
npx mudslide@latest send me 'message text here' --footer 'this is footer text'
```
works for me. 
I'm using the iOS app, I don't have access to an Android phone atm.

**Comment by lightaffaire** [comment]
I just retried this on 0.17.1 and the issue is still there... no footer text is visible.

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

On iOS I now only get a footer when including buttons, for example:

```shell
npx mudslide@latest send me 'message text here' -b yes -b no --footer 'this is footer text'
```

results in:
![IMG_3058](https://user-images.githubusercontent.com/5324924/226323433-c1d1585e-f9a1-449c-a350-9d1b8a3cd2de.jpg)

Previously I would also get a footer without buttons, but that no longer works.

I think this issue originates from the Baileys library (behavior changed when upgrading to the latest release of that library). Unfortunately, there's not much I can do about it.

**Comment by lightaffaire** [comment]
I just retried this on 0.18.0 and the issue is still there... no footer text is visible.
