### ISSUE TITLE
update help options to match the [options] text in listed commands

### ISSUE THREAD

**Issue by lightaffaire** [robvanderleek/mudslide#28]
Options: area of help should be expanded to list:

--caption
--footer

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

Options are expanded in the help message of specific commands, for example:

```shell
$ npx mudslide@latest send --help
Usage: mudslide send [options] <recipient> <message>

Send message

Options:
  -b, --button <text>  Button text (repeatable option) (default: [])
  --footer <text>      Footer text
  -h, --help           display help for command
```

Does this answer your question?

**Comment by lightaffaire** [comment]
now you explain it here i can understand but this will be a support nightmare going forwards. A suggestion:

Add 'mudslide@latest command --help'  to basic help text and also list the commands before the options... also the --button text needs more explanation:

Usage: Usage: mudslide [options] [command]

Commands:
  login                                             Login to WhatsApp
  logout                                            Logout from WhatsApp
  me                                                Show current user details
  groups                                            List all your groups
  send [options] <recipient> <message>              Send message
  send-image [options] <recipient> <file>           Send image file
  send-file [options] <recipient> <file>            Send file
  send-location <recipient> <latitude> <longitude>  Send location
  add-to-group <group-id> <phone-number>            Add group participant
  remove-from-group <group-id> <phone-number>       Remove group participant
  help [command]                                    display help for command

Options:
  -V, --version                                     output the version number
  -c, --cache <folder>                              Override cache folder
  --proxy                                           Use HTTP/HTTPS proxy
  -h, --help                                        display help for command

Examples:
  mudslide@latest command --help

**Comment by robvanderleek** [comment]
Hi @lightaffaire 

The options in the global help are global options, so it's logical to have them before the commands (also, the order is not easy to change as it's enforced by [the CLI library I'm using](https://github.com/tj/commander.js/#automated-help)).

I've added some example command at the end of the global help, as you suggested, thanks!

KR, Rob
