### ISSUE TITLE
Getting Issue  Reading Pdf Files path 

### ISSUE THREAD

**Issue by chhajervikram** [robvanderleek/mudslide#32]
Hello 
Getting issuse in Reading path  after space it doesnot read the complete path  for ex. my file is in D:\Tmp\pdf\abc - Abc123.pdf   but  after D:\Tmp\pdf\abc  it doesnt read  .Please Solve the issuse  how to read the complete path of any file . 

Thank you
Vikram Chhajer  

 While Sending The File Getting this Error 
(c) Microsoft Corporation. All rights reserved.

C:\Users\vikra>npx mudslide@latest send-file 9193********* E:\Sync\P M GRUP\2223\PM IM\2223\Invoice\DN-2200008-abc.pdf
×  error     Could not read image file: E:\Sync\P

**Comment by weldance** [comment]
Specify the file path in quotes, for example:
npx mudslide@latest send-file 9193********* "E:\Sync\P M GRUP\2223\PM IM\2223\Invoice\DN-2200008-abc.pdf"

**Comment by chhajervikram** [comment]
weldance   the same error received 
C:\Users\Admin>npx mudslide@latest  send-file 919320124688 "D:\CmsSync\Sync\Tejal\TEJAL 2223\2223\INVOICE\FSB2200002-2200002 - D B M"
×  error     Could not read image file: D:\CmsSync\Sync\Tejal\TEJAL 2223\2223\INVOICE\FSB2200002-2200002 - D B M

**Comment by weldance** [comment]
the file must have the extension?

**Comment by chhajervikram** [comment]
Thank You Problem Solved
