### ISSUE TITLE
Unable to send messages

### ISSUE THREAD

**Issue by zrkhan128** [robvanderleek/mudslide#33]
unable to send a message using the command npx mudslide@latest send me 'hello' after executing the command, I get the response as 'success Done' but on the WhatsApp app no message was received.

**Comment by weldance** [comment]
Noticed the same behavior. In addition, the message comes to the WhatsApp web interface

**Comment by robvanderleek** [comment]
For me, it works without issues on Web and the iOS app.
Unfortunately, I currently don't have access to an Android device for testing.
@zrkhan128 Does the message arrive for you on the Web interface, and what mobile platform are you using?

**Comment by zrkhan128** [comment]
I am using android, WhatsApp Desktop app is installed on my PC but nothing appear there too.

**Comment by zrkhan128** [comment]
@robvanderleek it was working perfectly fine before, I did install new window on the system since then i am facing this issue. other commands are working fine like list groups etc.

**Comment by zrkhan128** [comment]
I can see the message being delivered on the web interface but the recipent didn't recieve the message neither i can see it on my mobile device.

**Comment by robvanderleek** [comment]
Hi @zrkhan128 @weldance 

I had limited time to look at the behavior on Android. 
Indeed messages did not arrive (or are not received correctly, or just not shown).
It has something to do with the buttons, for now, I've pulled the code apart a bit, and sending plain messages should work again on Android, can you please verify with version 0.17.1?

**Comment by zrkhan128** [comment]
Now it's working fine thank you!
