### ISSUE TITLE
How to Update the Vesrion

### ISSUE THREAD

**Issue by chhajervikram** [robvanderleek/mudslide#34]
I m trying to update the muslide version from 11 to 12 but my all system have been updated to 12 but one system still showing 11 how to update from 11 to updated version . is their any command to update if then please share the command .

**Comment by robvanderleek** [comment]
Hi @chhajervikram 

With the `npx` command it will check for updates and download new updates automatically if you use the `@latest` suffix:
```
npx mudslide@latest -V
```

The [binaries on GitHub](https://github.com/robvanderleek/mudslide/releases/latest) are built infrequently and need to be downloaded manually.

Hope this helps, Rob
