### ISSUE TITLE
Will Old Command not work in latest version

### ISSUE THREAD

**Issue by chhajervikram** [robvanderleek/mudslide#37]
Hello 
As I have been Running Mudslide V 0.12  but now its updated to 0.18  , now want to know that old command  npx mudslide [command] will not run in the updated version as i am facing isssue  that some messages are delivery some not  . Is Old Command line not working 

Thank You 
Vikram

**Comment by robvanderleek** [comment]
Hi @chhajervikram 

Do you have an example of an old command that's no longer working?
I did recently merge the user and group commands, for example, before there was `send` and `send-group`, now there's only `send`.

Please have a look at the [Readme](https://github.com/robvanderleek/mudslide#readme) for all current commands.
