### ISSUE TITLE
New lines not adding to any messages!

### ISSUE THREAD

**Issue by horapusa-lk** [robvanderleek/mudslide#4]
i tried to message contain new lines. but it doesn't work properley.

**Comment by robvanderleek** [comment]
Hi @horapusa-lk 

Can you describe what command you tried?
This works for me:
```
npx mudslide send me 'hello\nworld'
```

**Comment by horapusa-lk** [comment]
thanks it works. sorry for the disturb sir!.

**Comment by robvanderleek** [comment]
No problem 🙂 I've added your question to the [Readme](https://github.com/robvanderleek/mudslide#sending-a-message-to-yourself-or-a-phone-number) 👍
