### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by LiveITA** [robvanderleek/mudslide#40]
<img width="749" alt="Screenshot 2023-04-27 at 13 59 49" src="https://user-images.githubusercontent.com/22427467/234772629-bc295681-0506-4f7c-aaa1-a1c898ca937a.png">
Hey, i am trying to install it but it keeps failing. What can i do?
Ubuntu server on AWS

happens when i run "sudo npm install -g mudslide" 

 "npx mudslide@latest -V" gave me this

<img width="827" alt="Screenshot 2023-04-27 at 14 02 13" src="https://user-images.githubusercontent.com/22427467/234773244-4221b2d5-0ea0-4805-891d-0f8383c9c50a.png">

**Comment by robvanderleek** [comment]
Hi @LiveITA 👋 

This might resolve the first error:

```shell
git config --global url."https://github".insteadOf ssh://git@github
```

The line above was also necessary in [the Docker build](https://github.com/robvanderleek/mudslide/blob/main/Dockerfile) of Mudslide.
