### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by luke432** [robvanderleek/mudslide#41]
Hi,
first thing first, 
I was looking for something like "mudslide" and it actually works
but I have a question: Is there a way to implement the possibility to receive messages from whatsapp users,
from the command line?

, 
Thank you 
I hope you will continue to update this project!

**Comment by robvanderleek** [comment]
Hi @luke432 

The goal of this project is to provide a simple CLI for sending messages.

If you want to receive messages I suggest directly using [this WhatsApp library](https://github.com/WhiskeySockets/Baileys#connecting).
An alternative is to use a library specifically for building bots, such as [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js).

HTH, Rob

**Comment by saitkaralar** [comment]
lost connection and cannot login anymore.  connection errored message receiving.
has any idea?

**Comment by robvanderleek** [comment]
Hi @saitkaralar 

Unfortunately, this sometimes happens, can you try the [troubleshooting steps](https://github.com/robvanderleek/mudslide#troubleshooting)?

**Comment by saitkaralar** [comment]
> Hi @saitkaralar
> 
> Unfortunately, this sometimes happens. Can you try the [troubleshooting steps](https://github.com/robvanderleek/mudslide#troubleshooting)?

Tried, still same. Actually what is intresting is: Can connect it to standart Whatsapp user, but cannot connect to whatsapp business number. Also some standart other user cannot connect too.
Error shown is:  ,"trace":"Error: Connection Failure\n    at WebSocket.<anonymous> (/usr/local/lib/node_modules/mudslide/node_modules/@adiwajshing/baileys/lib/Socket/socket.js

As I see, @adiwajshing/baileys is not in github anymore also.
Whatsapp business account connection lost and cannot connect (login) at the moment, btu can login with presonal wp.

**Comment by saitkaralar** [comment]
Seems so. If any alternative has instead of  Baileys library, may be updated later.
At the moment, have to change system from business account to normal to be able to make it working.
best regards

**Comment by robvanderleek** [comment]
I've [switched](https://github.com/robvanderleek/mudslide/pull/47) to an alternative library.
Please use the WA business API for commercial activities.
