### ISSUE TITLE
Git Error -4058 npm not able to find a file

### ISSUE THREAD

**Issue by ujayadev** [robvanderleek/mudslide#42]
Hi,
Thank you for your excellent utility.

Please see the attached error when trying to install mudslide on a Win 10 pro machine.
![MudslideError](https://github.com/robvanderleek/mudslide/assets/13509143/1fca7a8e-a747-4a0d-a2fa-38c682978183)

Please help.
Warm regards,

Jayadev

**Comment by robvanderleek** [comment]
Hi @ujayadev 👋 

I've seen this type of error before if you try to install Mudslide as a user that has no SSH access to GitHub (an external dependency of Mudslide is defined as an SSH link to a GitHub repo.)

A workaround that fixed my issue was to first run:
```shell
git config --global url."https://github".insteadOf ssh://git@github
```
and then try the install again.

Could you give this a try please?

**Comment by ujayadev** [comment]
Hi,

 

Thanks so much for your prompt reply.

 

I had to install git on the machine and the error resolved by itself.

 

Is installing Git compulsory or is there a work around ?

 

Warm regards,

 

Jayadev

**Comment by robvanderleek** [comment]
Aha, yes, Git is also needed due to this repo dependency.

Great you fixed it 😄
