### ISSUE TITLE
Mudslide stopped working.

### ISSUE THREAD

**Issue by lrufato** [robvanderleek/mudslide#43]
Mudslide stopped to work today.
Commands entered does not leave any output, and the messagens aren´t sent.
I hope this command helps.
Thank you very much.

EDITED@whatsapp:~$ npx mudslide@latest -vvv me
Cache folder: /home/EDITED/.local/share/mudslide
{"level":30,"time":1684983897620,"pid":5432,"hostname":"whatsapp","browser":["Linux","Chrome","10.15.0"],"helloMsg":{"clientHello":{"ephemeral":"lC1JEjcWoJng5eLFM1MdLrE51i5Plm1KucMpw7NaQxQ="}},"msg":"connected to WA Web"}
{"level":10,"time":1684983897763,"pid":5432,"hostname":"whatsapp","class":"ns","msg":"recv 350 bytes, total recv 350 bytes"}
{"level":10,"time":1684983897763,"pid":5432,"hostname":"whatsapp","class":"ns","msg":"recv frame"}
{"level":10,"time":1684983897764,"pid":5432,"hostname":"whatsapp","handshake":{"serverHello":{"ephemeral":"A/qH6uAWuGmg5Gx61RvtsSNjpqh2WtKR+GmApNMRFU4=","static":"u4zrByVSSqe8XUNehp6oqbTQo52D/XCftrJqGw4658W/FJFgea50w9sFdJBcAud/","payload":"TkARipn0fxlztxxp/+N6tDzOb7SB5CHRZLXlxs1Mi4gk1je/NTQix1ahHrto4g9XdFil5C+6TmcAoTuhD0m0ThD2qxIHjp4ow39XIZZl8kP8MdDRxkUFCxURnd50c8Z+8eURu1Kn3t0UxZ4/+Hgo39NPh8tqoFQ2XZ4XEAwVabwYYCKl93W8qoMFZIBVhfYrJoUTT2/+TDQIPVDyQzIjJChWawzM+BWEnKofg4VhWA4Wk5dG5sEz/k/eQM50UEaHOjS6B5JejPpWS/S2gKMges0FrxjGFjIg6czjH72vdcNI+aUiqwhoYX6ERWo+Y4meWBogNtv2QJZ8b21MNUt3H0k="}},"msg":"handshake recv from WA Web"}
{"level":30,"time":1684983897771,"pid":5432,"hostname":"whatsapp","node":{"username":"EDITED","passive":true,"userAgent":{"platform":"WEB","appVersion":{"primary":2,"secondary":2243,"tertiary":7},"mcc":"000","mnc":"000","osVersion":"0.1","manufacturer":"","device":"Desktop","osBuildNumber":"0.1","releaseChannel":"RELEASE","localeLanguageIso6391":"en","localeCountryIso31661Alpha2":"US"},"webInfo":{"webSubPlatform":"WEB_BROWSER"},"connectType":"WIFI_UNKNOWN","connectReason":"USER_ACTIVATED","device":13},"msg":"logging in..."}
{"level":10,"time":1684983897986,"pid":5432,"hostname":"whatsapp","class":"ns","msg":"recv 40 bytes, total recv 40 bytes"}
{"level":10,"time":1684983897987,"pid":5432,"hostname":"whatsapp","class":"ns","msg":"recv frame"}
{"level":10,"time":1684983897987,"pid":5432,"hostname":"whatsapp","fromMe":false,"frame":{"tag":"failure","attrs":{"reason":"401","location":"rva"}},"msg":"communication"}
{"level":30,"time":1684983897987,"pid":5432,"hostname":"whatsapp","trace":"Error: Connection Failure\n    at WebSocket.<anonymous> (/home/EDITED/.npm/_npx/ce95761724e6020f/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:429:13)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at /home/EDITED/.npm/_npx/ce95761724e6020f/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35\n    at Object.decodeFrame (/home/EDITED/.npm/_npx/ce95761724e6020f/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)\n    at WebSocket.onMessageRecieved (/home/EDITED/.npm/_npx/ce95761724e6020f/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15)\n    at WebSocket.emit (node:events:513:28)\n    at WebSocket.emit (node:domain:489:12)\n    at Receiver.receiverOnMessage (/home/EDITED/.npm/_npx/ce95761724e6020f/node_modules/ws/lib/websocket.js:1184:20)\n    at Receiver.emit (node:events:513:28)","msg":"connection errored"}

**Comment by robvanderleek** [comment]
Hi @lrufato 

Sorry to hear and thanks for sending the detailed logs.

Unfortunately, I can't make up from the logs what goes wrong. I just tested Mudslide myself and it still works (note that Mudslide depends on a 3rd-party library to work properly and this library is not officially supported by Meta.)

Can you try to logout (optionally purge the cache folder), remove the connection to Mudslide in your WA mobile app, and login again?

HTH, Rob

**Comment by lrufato** [comment]
You are right.
Deleting cache directory and logging in again fixed the issue.
Thank you very much for you quick and kind response and sorry for taking your time with a very basic issue.
Luiz.

**Comment by robvanderleek** [comment]
No problem at all, the issue is actually not so basic as I don't know what causes this behavior (I think the problem is in the library I'm using).
Clearing the cache is just a workaround, it would be better if the user at least got a more descriptive error message or Mudslide would be able to recover by itself from this situation (as it can be annoying to periodically clean the cache/logout/login/etc.)

Thanks for reporting!
