### ISSUE TITLE
Spaces in Path or file name not supported when sending image or document

### ISSUE THREAD

**Issue by ujayadev** [robvanderleek/mudslide#44]
Hi,

Thanks from closing issue no. 42.  The program is working correctly now.  However, I now find that when sending image or document spaces either in path of file name is not supported.  I am working in Windows environment.

Consider the following path for an image:
H:\Billing\Images\Do not delete\Albroz\Adlid\Adlid 13.jpg

Mudslide is not able to send this as there are spaces in the directory name and the file name.

How to overcome this ?

Warm regards,

Jayadev

**Comment by robvanderleek** [comment]
Hi @ujayadev 👋 

Your issue sounds similar to [this issue](https://github.com/robvanderleek/mudslide/issues/32).
Can you check if quoting the filename helps?
Spaces in filenames can be challenging 😉  and it depends per shell on how to handle them properly.

Good luck,
Rob

**Comment by ujayadev** [comment]
Thanks so much Rob.

Personally, I think, if we make a note of this in readme.md it will help
solve many such queries in future.
Suggested Modification to readme.md:
Note: in case there is space in path or in file name, please enclose the
entire path and file name in quotes (")

Secondly, now I have put the program to use, I have been requested by users
to allow multiple attachments in the same message.  Is this possible?  What
would be the syntax ?

Once again thanks for the excellent utility.

Warm regards,

Jayadev

**Comment by robvanderleek** [comment]
Hi @ujayadev 

Great suggestion, I've [include a note in the Readme](https://github.com/robvanderleek/mudslide#sending-an-image-file), twice 😉  

I've checked the [WA library](https://github.com/WhiskeySockets/Baileys) I'm using but unfortunately I couldn't find support for sending multiple attachments to a single message.

KR, Rob

**Comment by ujayadev** [comment]
Hi Rob,

Thanks so much. I saw your note in GitHub.

If it is not inconvenient, please rephrase as under:
in case there is space in path or in file name,

(file name part is missing and can create confusion)

>>I've checked the WA library <https://github.com/WhiskeySockets/Baileys>
I'm using but unfortunately I couldn't find support for sending >>multiple
attachments to a single message.

Ok, I will loop and send separate a message for each attachment for the
time being, but sending a message with multiple attachments I think is a
desirable feature.  Maybe you can point out to the developers.

Warm regards,

Jayadev

**Comment by robvanderleek** [comment]
> Hi Rob, Thanks so much. I saw your note in GitHub. If it is not inconvenient, please rephrase as under: in case there is space in path or in file name, (file name part is missing and can create confusion)

Done 🙂 

>multiple attachments to a single message. Ok, I will loop and send separate a message for each attachment for the time being, but sending a message with multiple attachments I think is a desirable feature. Maybe you can point out to the developers.

I'm using whatever the library provides but you can always [open an issue](https://github.com/WhiskeySockets/Baileys/issues) in the library and let me know if I missed something or when it's implemented.

Be aware that Mudslide can stop working without notice since it depends on libraries that could be removed any time from GitHub/NPM, so do not use it for important/commercial things.

All the best, Rob
