### ISSUE TITLE
Docker Run / Login command missing image name 

### ISSUE THREAD

**Issue by BobbieERay** [robvanderleek/mudslide#49]
Hi , thanks so much for putting this together. I followed the instructions to build and run the container image. However, I feel that the command to start the container and run the login command should read
```bash
docker run -v /home/<USERNAME>/.local/share/mudslide:/usr/src/app/cache mudslide login
```

The image name, i.e. mudslide, appears to be missing in the Readme.

Cheers

**Comment by robvanderleek** [comment]
Hi @BobbieERay 👋 

You are right, I've updated the Readme, thanks!

KR, Rob
