### ISSUE TITLE
Cannot use new line "\n" in Image caption

### ISSUE THREAD

**Issue by kingsansuen** [robvanderleek/mudslide#50]
"\n" new line works perfectly fine in send message.
But I can's seem to do the same for image caption.
It will just appear as text instead of breaking a new line.
Just wonder if there is a way to get around it or will you implement this in future?
Thank you!

**Comment by robvanderleek** [comment]
Hi @kingsansuen 

You are right, newlines were not handled properly for captions.
I've fixed the issue in the latest release (0.20.1).
Let me know if things don't work as expected, thanks for reporting!

KR, Rob
