### ISSUE TITLE
Audio and video upload!

### ISSUE THREAD

**Issue by AprendendoLinux** [robvanderleek/mudslide#52]
**Dear,**

I start by apologizing, because I'm Brazilian and I'm still learning to write in English. I found this fantastic solution.

I would like to know how I can send *.mp3 or *.ogg audios with this solution. I would also like to be able to upload videos.

I'm waiting for responses.

Yours sincerely,

**[Henrique Fagundes](https://www.henrique.tec.br)**
Project Manager [Aprendendo Linux](https://www.aprendendolinux.com)

**Comment by AprendendoLinux** [comment]
**Hi @robvanderleek,**

Sorry for the delay in responding. I was away from my professional activities for family reasons.

So, my need is to send audio, without being in file mode. I want the recipient to simply click inside the play button within Whatsapp to listen to it.

Yours sincerely,

[Henrique Fagundes](https://www.henrique.tec.br/)
Project Manager [Aprendendo Linux](https://www.aprendendolinux.com/)

**Comment by robvanderleek** [comment]
Hi @AprendendoLinux 

I've added a `--type` flag to the `send-file` command, this will cause audio and video files to be rendered as playable messages in WhatsApp. Please see the [README](https://github.com/robvanderleek/mudslide#file-types) for details.

Let me know if this works for your use-case.

KR, Rob

**Comment by AprendendoLinux** [comment]
Hi @robvanderleek,

Thank you so much for this!
You don't know how much you've helped me.

I took the liberty of putting your solution in a docker container, to make other people's lives easier.
[https://github.com/AprendendoLinux/whatscli](https://github.com/AprendendoLinux/whatscli)

Yours sincerely,

[Henrique Fagundes](https://www.henrique.tec.br/)
Project Manager [Aprendendo Linux](https://www.aprendendolinux.com/)

**Comment by robvanderleek** [comment]
Hi @AprendendoLinux 

Great to hear it works for you 🙂 

Be aware that WA (Meta) might block access for the [Baileys](https://github.com/WhiskeySockets/Baileys) library (this project depends on) at any time, they can also ban accounts, so don't become too dependent on it.

Kind regards, Rob
