### ISSUE TITLE
Latest version (0.21.0) fails in Windows 11 64bit stable

### ISSUE THREAD

**Issue by reddyshyam** [robvanderleek/mudslide#54]
Throws below error on command line

mudslide.exe login
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './718.index.js'
Require stack:
- C:\snapshot\dist-ncc\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.require (C:\snapshot\dist-ncc\index.js)
    at C:\snapshot\dist-ncc\index.js
    at Array.reduce (<anonymous>)
    at Function.e (C:\snapshot\dist-ncc\index.js) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\snapshot\\dist-ncc\\index.js' ],
  pkg: true
}

**Comment by robvanderleek** [comment]
Hi @reddyshyam 

This seems to be an issue with the bundler ([ncc](https://github.com/vercel/ncc)) and the packager ([pkg](https://github.com/vercel/pkg)) I'm using.
A summary of my understanding: the packager does not support ESM modules (that some of the third-party libraries from Mudslide use), so I first need to bundle everything using CommonJS modules. However, the bundler generates dynamic `require` statements that are problematic for some platforms.

I've now explicitly added all the JS files to the Windows in binary, maybe that helps. I don't have access to a Windows platform so please try the [0.21.1 release](https://github.com/robvanderleek/mudslide/releases/tag/0.21.1) and let me know.

**Comment by reddyshyam** [comment]
> Hi @reddyshyam
> 
> This seems to be an issue with the bundler ([ncc](https://github.com/vercel/ncc)) and the packager ([pkg](https://github.com/vercel/pkg)) I'm using. A summary of my understanding: the packager does not support ESM modules (that some of the third-party libraries from Mudslide use), so I first need to bundle everything using CommonJS modules. However, the bundler generates dynamic `require` statements that are problematic for some platforms.
> 
> I've now explicitly added all the JS files to the Windows in binary, maybe that helps. I don't have access to a Windows platform so please try the [0.21.1 release](https://github.com/robvanderleek/mudslide/releases/tag/0.21.1) and let me know.

Works like a charm👌though exe has become bulky but understandable. Thanks for the quick resolution. 🙏👏
