### ISSUE TITLE
x86 pre-compiled not working again....

### ISSUE THREAD

**Issue by WolfRamiO74** [robvanderleek/mudslide#56]
So...i updated fron 0.20.1 that was working perfect to the last version of x86_64 for linux and now i am getting this error (dependency problem?), i tried to fix it removing the data/config folder but didnt work. 

```
root@server:~/scripts/wsp# ./mudslide-linuxstatic-x64 login
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './718.index.js'
Require stack:
- /snapshot/dist-ncc/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.require (/snapshot/dist-ncc/index.js)
    at /snapshot/dist-ncc/index.js
    at Array.reduce (<anonymous>)
    at Function.e (/snapshot/dist-ncc/index.js) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/snapshot/dist-ncc/index.js' ],
  pkg: true
}
root@server:~/scripts/wsp#

```

**Comment by robvanderleek** [comment]
Hi @WolfRamiO74 

I think this issue is similar to https://github.com/robvanderleek/mudslide/issues/54

I've included the JS assets also for the Linux build, can you check [the latest release](https://github.com/robvanderleek/mudslide/releases/tag/0.21.2) please?

**Comment by WolfRamiO74** [comment]
> Hi @WolfRamiO74
> 
> I think this issue is similar to #54
> 
> I've included the JS assets also for the Linux build, can you check [the latest release](https://github.com/robvanderleek/mudslide/releases/tag/0.21.2) please?

thanks!!!! working again, only message that i get when do the login was this:

`success   Logged in
◼  pause     Wait until WhatsApp finishes connecting, then press any key to exit
(node:920) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `mudslide-linuxstatic-x64 --trace-deprecation ...` to show where the warning was created)`

**Comment by robvanderleek** [comment]
Great 🙂 
I think the deprecation warning comes from a library I'm using, there's no use of `Buffer` in the Mudslide code. I'll wait until it's resolved in the library.

**Comment by robertwho** [comment]
Sadly this is happening again with the latest release 0.29.0

`# ./mudslide-linuxstatic-x64 login
ℹ  info      In the WhatsApp mobile app go to "Settings > Connected Devices >
ℹ  info      Connect Device" and scan the QR code below
Created mudslide cache folder: /root/.local/share/mudslide
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './718.index.js'
Require stack:
- /snapshot/dist-ncc/index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.require (/snapshot/dist-ncc/index.js)
    at /snapshot/dist-ncc/index.js
    at Array.reduce (<anonymous>)
    at Function.e (/snapshot/dist-ncc/index.js) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/snapshot/dist-ncc/index.js' ],
  pkg: true
}`

**Comment by robvanderleek** [comment]
Hi @robertwho 

I've switched to a different bundler (from ncc to esbuild), hopefully that fixes these (reoccurring) issues.
Can you try the binaries from the [latest release (0.29.2)](https://github.com/robvanderleek/mudslide/releases/tag/0.29.2)?

**Comment by robertwho** [comment]
@robvanderleek excellent, v29.2 works as supposed to do! Thank you very much
