### ISSUE TITLE
banning numbers

### ISSUE THREAD

**Issue by Solutionkw** [robvanderleek/mudslide#59]
hi , thank you , it working well , but my number banned after first message to me , plz what to avoid the banning

**Comment by robvanderleek** [comment]
Hi @Solutionkw 

Sorry to hear you got banned.
Mudslide is just a thin wrapper around [the unofficial WA library called Baileys](https://github.com/WhiskeySockets/Baileys). Please check that library for issues such as banning, for example as discussed in [this issue](https://github.com/WhiskeySockets/Baileys/issues/225).

KR, Rob

**Comment by Solutionkw** [comment]
thank you very much ,, it working well,, but my number where reported
