### ISSUE TITLE
Message New Line issue

### ISSUE THREAD

**Issue by zrkhan128** [robvanderleek/mudslide#6]
When I try to add new line character as '\n' single slash replaces with double slash.

**Comment by robvanderleek** [comment]
Hi @zrkhan128 

You can send [newlines using `\n`](https://github.com/robvanderleek/mudslide#sending-a-message-to-yourself-or-a-phone-number) but be careful your shell is not replacing any characters.

What shell command are you using?

**Comment by zrkhan128** [comment]
this is my command npx send 923159839893 'hello\nworld'
This is what I get attaching a screenshot.

**Comment by robvanderleek** [comment]
Hi @zrkhan128 

I've removed your comment since it might contain your phone number?

This command works for me:

```shell
npx mudslide@latest send me 'hello\nworld'
```

<img width="209" alt="image" src="https://user-images.githubusercontent.com/5324924/216012929-9a92cba3-e315-4ed2-b2c8-c38b360a73d4.png">

**Comment by zrkhan128** [comment]
Thank you for your prompt response.
