### ISSUE TITLE
issue with adding ppl to group

### ISSUE THREAD

**Issue by WolfRamiO74** [robvanderleek/mudslide#61]
Hi there, i am tring to add people to a group using mudslide but nothing happend, after some time i get this; 
(i replace some numbers with an X to post here)

root@server:/var/www/html/wsp# ./mudslide-linuxstatic-x64 -c cache add-to-group 120363029818944716@g.us  +5XXX78355X8
Adding +5X9XXX35X58@s.whatsapp.net to group 120X63X2981X9X4X16@g.us
/snapshot/dist-ncc/index.js:99126
            .then(() => reject(new boom_1.Boom('Timed Out', {
                               ^

Error: Timed Out
    at /snapshot/dist-ncc/index.js:99126:32 {
  data: {
    stack: 'Error\n' +
      '    at promiseTimeout (/snapshot/dist-ncc/index.js:99121:19)\n' +
      '    at waitForMessage (/snapshot/dist-ncc/index.js:95558:53)\n' +
      '    at query (/snapshot/dist-ncc/index.js:95580:22)\n' +
      '    at groupQuery (/snapshot/dist-ncc/index.js:93575:55)\n' +
      '    at Object.groupParticipantsUpdate (/snapshot/dist-ncc/index.js:93705:34)\n' +
      '    at /snapshot/dist-ncc/index.js:159:30\n' +
      '    at Generator.next (<anonymous>)\n' +
      '    at fulfilled (/snapshot/dist-ncc/index.js:13:58)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
  },
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 408,
    payload: {
      statusCode: 408,
      error: 'Request Time-out',
      message: 'Timed Out'
    },
    headers: {}
  }
}

**Comment by robvanderleek** [comment]
Hi @WolfRamiO74 

I've done some basic tests and group adding/removing seems to work fine for me.
You don't need to prefix numbers with a `+` symbol, actually that doesn't work, can you try without the `+`?
Also, are you using the [latest static build](https://github.com/robvanderleek/mudslide/releases/tag/0.21.2)?

**Comment by WolfRamiO74** [comment]
Hi, thanks, was the "+" character before number...

**Comment by robvanderleek** [comment]
Great to hear your problem is resolved 🙂 
I've added [some code to strip the plus sign](https://github.com/robvanderleek/mudslide/pull/64) so future users don't run into the same issue.
