### ISSUE TITLE
New Line have char "\"

### ISSUE THREAD

**Issue by apie08** [robvanderleek/mudslide#62]
Why after I execute the command with new line, I got "\\" after that?

Example :

npx mudslide send me "Hello \\nWorld"

Return:

Hello \\
World

**Comment by robvanderleek** [comment]
Hi @apie08 

I think you need to escape the slash when using double quotes, or replace the double quotes by single quotes.

So, try this:

```shell
npx mudslide send me "Hello \\nWorld"
```

Or:

```shell
npx mudslide send me 'Hello \nWorld'
```

**Comment by apie08** [comment]
This is my code. I'm using C# to open CMD and run the command.
![image](https://github.com/robvanderleek/mudslide/assets/15040317/a5965afa-507e-4077-8b47-ded2321d9334)

But it's not working when using single quotes. I have tried it

**Comment by robvanderleek** [comment]
I think this is a C# specific problem, I've just checked `npx mudslide send me 'hello\nworld'` and `npx mudslide send me "hello\\nworld"` in the shell and that works fine.
Escaping characters for sub-processes can be tricky, maybe you need `\\\\n` for it to work but I'm not sure. I'm not using C# myself so can't help you more with this issue.

**Comment by apie08** [comment]
Or is it because node js version? because I'm using veesion 16

**Comment by apie08** [comment]
Problem solved. Solution is node JS version is not version 18 or latest. Thank you

**Comment by robvanderleek** [comment]
Great to hear!
I'm closing this issue then 🙂
