### ISSUE TITLE
Sending Location Message

### ISSUE THREAD

**Issue by coccovax** [robvanderleek/mudslide#7]
It would be nice to send location message too.

**Comment by robvanderleek** [comment]
Hi @coccovax 

Thanks for your feature request.

It's possible in the WhatsApp API library I'm using to [send a location](https://adiwajshing.github.io/Baileys/#sending-messages) but it requires the position in latitude and longitude degrees. I then wonder how this would work in practice: would users first lookup a location coordinate, or would they expect a comnand-line tool to get that information from the OS.

Could you perhaps tell me a bit more about your use case?

**Comment by coccovax** [comment]
Hi @robvanderleek,
thanks for your reply.
My use case involves always fixed coordinates known to the system. When a user books a service, she receives a message with instructions for using it. Having the location in the message would also be very nice.

**Comment by robvanderleek** [comment]
Hi @coccovax 

I've added a new feature for sending a location message [in this pull-request](https://github.com/robvanderleek/mudslide/pull/9)

If you know how to checkout the repository and run the application using `yarn start` it would be helpful to let me know if this works for you. 
Otherwise, no problem, I'll do a bit more testing/documentation and merge the pull-request soon.

**Comment by coccovax** [comment]
@robvanderleek thanks a lot. In this period I'm very busy, but I'll try to do the tests you ask for asap.

**Comment by coccovax** [comment]
Hi @robvanderleek,
I did some tests and location is sent only if coordinates are positive and there are max 4 decimals. I used this coordinates for testing `-33.8677835,-63.9863332`.
The result is:

- [ ] negative coordinates must be allowed
- [ ] if possible, manage more than 4 decimals

Thank a lot

**Comment by robvanderleek** [comment]
Thanks for the testing @coccovax!

I've fixed the issues, also [see the README](https://github.com/robvanderleek/mudslide/tree/issue-7-Sending_Location_Message#sending-a-location).

Can you give it another try please?

**Comment by coccovax** [comment]
Hi @robvanderleek, good job!
It worked for me!
Thanks a lot!

**Comment by robvanderleek** [comment]
Cool! I'll merge it main then 😄
