### ISSUE TITLE
Send image along with text message

### ISSUE THREAD

**Issue by zrkhan128** [robvanderleek/mudslide#76]
I want to send text message with image currently the flow is like to attach file and put caption which is working fine but in that case user have to click manually to download and see the image. what i want is that user do not click on the image to download and see the image, it should be downloaded by default same like we do using WhatsApp on phone. Please guide me if there is any workaround through which i can establish this.

**Comment by robvanderleek** [comment]
Hi @zrkhan128 

The use-case that you describe should display the image immediately, for example:

```shell
npx mudslide send-image me tuesday.png --caption "It's Tuesday"
```

displays the PNG with a caption text on my WA iOS App.

It could be that large files or other file types require a click to download, can you give an example your command and the image file?

**Comment by SproAdmin** [comment]
Hi there,
I'm trying to use Mudslide in a bash script (ubuntu 22.04) as follows:

#!/bin/bash
number="4312345678910"
content="hello world 111"
npx mudslide send $number "hello world 111"
npx mudslide send $number $content

The first mudslide commands sends:       hello world 111
The second mudslide command sends:   'hello

Could anyone tell me, what I#m doing wrong? Thanx and regards
Volkmar

**Comment by zrkhan128** [comment]
npx mudslide@latest send-image me image.png
I am using this command let me try the one you mentioned.
