### ISSUE TITLE
QR CODE

### ISSUE THREAD

**Issue by Anayaali2019** [robvanderleek/mudslide#83]
is there any way to get QR CODE as image format
i am trying to connect with my wordpress website but unable to fatch QR code

**Comment by robvanderleek** [comment]
Hi @Anayaali2019 

Mudslide is based on the Baileys library and as far as I can find that only supports [printing the QR code to the terminal/stdout](https://github.com/WhiskeySockets/Baileys?tab=readme-ov-file#connecting-multi-device-recommended).

Maybe you can pipe the output to a program that can generate an image from it?

**Comment by Anayaali2019** [comment]
https://github.com/Anayaali2019/WhatsPress-Helper

**Comment by robvanderleek** [comment]
Hi @Anayaali2019 

That's a nice spinoff project, good luck with development 🙂 

I'm not a Wordpress user so my knowledge about it is close to zero, but in any case, be careful not to put WA credentials on places that are publicly accessible.

Kind regards, Rob
