### ISSUE TITLE
Mudslide multi configuration 

### ISSUE THREAD

**Issue by Anayaali2019** [robvanderleek/mudslide#84]
Once again here
I am trying to use mudslide configuration with multiple profiles like
Profile one
./mudslide send me "ok1" -c ~/03356105927

Profile two
./mudslide send me "ok2" -c ~/035668908

Both login successfully

 send msg from 1st profile work fine 
But on 2nd profile it show login QR again

**Comment by robvanderleek** [comment]
Hi @Anayaali2019 

I've just tested this and it seems to keep the profiles separated.
Maybe it works if you put the cache option before the command:

```
./mudslide -c /some/path/here send me "hello world"
```
