### ISSUE TITLE
what is needed in the cache folder?

### ISSUE THREAD

**Issue by mkgitalia** [robvanderleek/mudslide#85]
I realized that the cache folder can get large. What is needed and what can be deleted in this folder? Thank you

**Comment by robvanderleek** [comment]
Hi @mkgitalia 

Mudslide uses the [Baileys library](https://github.com/WhiskeySockets/Baileys) for communication with WA. That library provides a [file based store](https://github.com/WhiskeySockets/Baileys?tab=readme-ov-file#saving--restoring-sessions) for saving and loading of credentials. I don't know which of the files in the store are active and which are stale, you would have to ask this question in the Baileys repository to get an answer.

KR, Rob
