### ISSUE TITLE
Issues sending images

### ISSUE THREAD

**Issue by danielpmd** [robvanderleek/mudslide#88]
Hello,

Sending text message is working great. The code below is ok:

`npx mudslide send 0000000000000 "test"`

However, I am having issues sending images. I tried the following command:

` npx mudslide send-image 0000000000000 car.png`

But at the receiver's WhatsApp the image was not received properly and user cannot open it (ckeck attached image).

![Screen](https://github.com/robvanderleek/mudslide/assets/64454324/98d844f3-89cd-470b-a96b-23812f714f78)

Could you assist me on that?

Regards.

**Comment by robvanderleek** [comment]
Hi @danielpmd 

Sorry to hear Mudslide is not working as expected.

I've just tried this command:
```shell
npx mudslide@latest send-image me Screenshot\ 2024-05-07\ at\ 15.48.54.png
```
and the image shows fine for me.

Can you perhaps try it with a different image? Or different format, such as JPEG?

**Comment by danielpmd** [comment]
Hello,

I tried with a different image file and it worked properly! I tried with both .jpg and .png (both worked). Maybe the previous file was corrupted. Sorry for that, my bad.

Just a question, whats the difference running mudslide with:

- mudslide
- mudslide@latest
- npx mudslide
- npx mudslide@latest

??

Regards.

**Comment by robvanderleek** [comment]
`npx` installs and runs a NodeJS package from https://npmjs.com. If you use the suffix `@latest` then `npx` will always check if there's a more recent version available, if you don't use that suffix a version from your cache is used.

There are also [binaries released](https://github.com/robvanderleek/mudslide/releases/tag/0.25.2) for every mudslide version that you can use, these are called `mudslide.exe`, `mudslide-linuxstatic-x64` etc. 

Hope this answers your questions.

**Comment by danielpmd** [comment]
Thanks a lot for your support.
