### ISSUE TITLE
Upgrade request

### ISSUE THREAD

**Issue by mkgitalia** [robvanderleek/mudslide#89]
There’s a way to omit upgrade blocking prompt like “Need to install following packages…”? Thanks

**Comment by robvanderleek** [comment]
Hi @mkgitalia 

What command are you using to upgrade?

**Comment by mkgitalia** [comment]
I only send a message, but send command is blocked by upgrade request.

**Comment by robvanderleek** [comment]
Can you show the exact command you're using please?

**Comment by mkgitalia** [comment]
npx mudslide@latest send me 'hello world from linux'

**Comment by robvanderleek** [comment]
You can use the `-y` flag from `npx` to answer "yes" by default on `npx` questions:

```shell
npx -y mudslide@latest send me 'hello world from linux'
```

**Comment by mkgitalia** [comment]
Thank!
