### ISSUE TITLE
QR code doesn't show up

### ISSUE THREAD

**Issue by 0xF0CACC1A** [robvanderleek/mudslide#90]
![image](https://github.com/robvanderleek/mudslide/assets/162066417/565d502e-a4df-442e-b645-671a0367d12a)

**Comment by robvanderleek** [comment]
Hi @0xF0CACC1A 

I can confirm this, I'll look into it.

Thanks for reporting

**Comment by robvanderleek** [comment]
Hi @0xF0CACC1A 

I was able to reproduce the problem by disconnecting `mudslide` in the WA App, and then run `mudslide login`.

What worked for me is to first run `mudslide logout` (this clears the authentication cache), and then run `mudslide login`.
Can you check if that also solves your issue?

**Comment by 0xF0CACC1A** [comment]
> Hi @0xF0CACC1A
> 
> I was able to reproduce the problem by disconnecting `mudslide` in the WA App, and then run `mudslide login`.
> 
> What worked for me is to first run `mudslide logout` (this clears the authentication cache), and then run `mudslide login`. Can you check if that also solves your issue?

![image](https://github.com/robvanderleek/mudslide/assets/162066417/1864d398-5cd9-4664-b8ac-5dd913033134)
Unlike you, I haven't disconnected mudslide in the WA App because I've never connected it before

**Comment by 0xF0CACC1A** [comment]
> > Hi @0xF0CACC1A
> > I was able to reproduce the problem by disconnecting `mudslide` in the WA App, and then run `mudslide login`.
> > What worked for me is to first run `mudslide logout` (this clears the authentication cache), and then run `mudslide login`. Can you check if that also solves your issue?
> 
> ![image](https://private-user-images.githubusercontent.com/162066417/332733252-1864d398-5cd9-4664-b8ac-5dd913033134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNzA5MTksIm5iZiI6MTcxNjM3MDYxOSwicGF0aCI6Ii8xNjIwNjY0MTcvMzMyNzMzMjUyLTE4NjRkMzk4LTVjZDktNDY2NC1iOGFjLTVkZDkxMzAzMzEzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwOTM2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmQ1ZjMyYTI1M2Y0NGVmMzQ1ODcyM2RlN2RkYjNmNWQ0ZGMzMjNkYjc2NGQyNDE0MjlhYzI4OGJiOTgxMjg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cHlLAcPr_bh-8hWXLNCyY3XHbN46mqvh5KMMFt5l0zg) Unlike you, I haven't disconnected mudslide in the WA App because I've never connected it before

Btw I'm (still) using version 0.25.2

**Comment by sri4** [comment]
Hi @robvanderleek,

First, thanks for the code with the easy installation and commands!

I have the same problem with the QR code generation. Previously, I was using version 0.25.2 and suddenly the command got stuck. I tried reinstalling with the latest version 0.25.3, but the QR code is still not generating, even after logging out and logging in again.

**Comment by lrufato** [comment]
Same here.

**Comment by mkgitalia** [comment]
I use login command with -v, please see image attached
![WALoginError](https://github.com/robvanderleek/mudslide/assets/3187597/1517ac97-7fa1-4636-af38-18b4e6e30034)

**Comment by budgetsms** [comment]
Could be related to this: https://github.com/WhiskeySockets/Baileys/pull/805

I am trying this patch, although not working (for me), I think it is related to new whatsapp web releases.

**Comment by cthiagotavares** [comment]
hi @robvanderleek 
It worked for me!!
Thank you very much!!

**Comment by lrufato** [comment]
If your system was messed up by latest bug, this is how I fixed my system and got it running fine again on latest version.

-> Debian 12.5 Bookworm.

This guide will uninstall all traces of nodejs, npm and installed modules on your system.

AS ROOT:  
npm uninstall mudslide/ 
apt purge npm nodejs -y
apt autoremove --purge -y
rm /usr/local/bin/mudslide
rm -rf /usr/local/lib/node_modules
rm -rf package* .npm/ node_modules/ mudslide/
rm /usr/bin/mudslide
rm -rf /usr/lib/node_modules
mudslide 
which mudslide
reboot
apt install npm

AS YOUR USER:
rm -rf node_modules/ package* .local/share/mudslide/
npm install mudslide

AS ROOT
cd /usr/local/bin/
ln -s /home/YOURUSER/node_modules/mudslide/dist/index.js mudslide

AS YOUR USER:
mudslide --version
mudslide login

TO UPDATE MUDSLIDE, AS REGULAR USER WHERE MUDSLIDE IS INSTALLED.
npm update mudslide -y

I hope someone find this useful.

robvanderleek: Thank you very much for your efforts.

**Comment by mkgitalia** [comment]
when I update I receve this message "npm WARN skipping integrity check for git dependency ssh://git@github.com/WhiskeySockets/Baileys.git"
and then when I try to login no QRCode appear

**Comment by cthiagotavares** [comment]
Hi @robvanderleek 

When trying to install it is returning the following error:
ERROR: failed to solve: process "/bin/sh -c npm install -g mudslide" did not complete successfully: exit code: 127

**Comment by robvanderleek** [comment]
Hi all,

Due to a [fix in the Baileys library](https://github.com/WhiskeySockets/Baileys/pull/805) that solves WA connection problems but have not yet been released, the latest version of Mudslide is now depending on [a GitHub repository hash](https://github.com/robvanderleek/mudslide/blob/920e93dc51d28a0a0622fc89050b0cf37293e12f/package.json#L43). This might give issues with `npx`, beyond my control.

FWIW, I can still install the latest version like this:

```shell
❯ npx mudslide me
Need to install the following packages:
mudslide@0.25.4
Ok to proceed? (y) y
npm WARN skipping integrity check for git dependency ssh://git@github.com/WhiskeySockets/Baileys.git
Cache folder: /Users/rob/.local/share/mudslide
Current user: ****:58@s.whatsapp.net
…  awaiting  Closing WA connection, waiting for 1 second(s)...
⭐ Please star Mudslide on GitHub! https://github.com/robvanderleek/mudslide

❯ npx --version
10.5.2
```

**Comment by robvanderleek** [comment]
Hi all,

Please check the newest release ([0.26.0](https://github.com/robvanderleek/mudslide/releases/tag/0.26.0)), this release has again a versioned dependency on the Baileys library.
