### ISSUE TITLE
Unbale To Upgrade mudslide  Version 25.4

### ISSUE THREAD

**Issue by chhajervikram** [robvanderleek/mudslide#92]
Sir 
When i use this  command to check the vesrion npx mudslide@latest -V
Need to install the following packages:
  mudslide@0.25.4
Ok to proceed? (y)
It Show This and i Press Y To update the programme but it doesnt update  , is their an issuse for Update . 

Thank You
Vikram

**Comment by lightaffaire** [comment]
I have the exact same problem since 2 days:

$ npx mudslide@latest send me hello
Need to install the following packages:
  mudslide@0.25.4
Ok to proceed? (y) y

$ npx mudslide@latest send me hello
Need to install the following packages:
  mudslide@0.25.4
Ok to proceed? (y)

Does not upgrade.

If i try to use 0.25.3 or 0.25.2 then it will downgrade but the message does not get sent... no output of sending text:

$ npx mudslide@0.25.3 send me hello
[ nothing is printed at all]

**Comment by robvanderleek** [comment]
Hi @chhajervikram @lightaffaire 

Due to a [fix in the Baileys library](https://github.com/WhiskeySockets/Baileys/pull/805) that solves WA connection problems but have not yet been released, the latest version of Mudslide is now depending on [a GitHub repository hash](https://github.com/robvanderleek/mudslide/blob/920e93dc51d28a0a0622fc89050b0cf37293e12f/package.json#L43). This might give issues with `npx`, outside my control.

FWIW, I can still install the latest version like this:

```shell
❯ npx mudslide me
Need to install the following packages:
mudslide@0.25.4
Ok to proceed? (y) y
npm WARN skipping integrity check for git dependency ssh://git@github.com/WhiskeySockets/Baileys.git
Cache folder: /Users/rob/.local/share/mudslide
Current user: ****:58@s.whatsapp.net
…  awaiting  Closing WA connection, waiting for 1 second(s)...
⭐ Please star Mudslide on GitHub! https://github.com/robvanderleek/mudslide

❯ npx --version
10.5.2
```

**Comment by chhajervikram** [comment]
Trying To install Mudslide  get this error   

C:\Users\vikra>npm install -g mudslide

npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\vikra\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\vikra\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\vikra\AppData\Local\npm-cache\_cacache\tmp\git-cloneXXXXXXJofsj6
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc
npm ERR! npm ERR! 'tsc' is not recognized as an internal or external command,
npm ERR! npm ERR! operable program or batch file.
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\vikra\AppData\Local\npm-cache\_logs\2024-05-28T01_28_58_166Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vikra\AppData\Local\npm-cache\_logs\2024-05-28T01_28_54_525Z-debug-0.log


Sir Create Exe File If Possible to Install the latest Version . Or Sir Please Help us How to reslove this issue .  

Thank You
Vikram Chhajer

**Comment by schleiche123** [comment]
I have the same problem updating from 0.25.3 to 0.25.4

# npm update -g mudslide

npm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/share/nodejs/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 127
npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-clonehcJ4vY
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c tsc
npm ERR! npm ERR! sh: 1: tsc: not found
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /root/.npm/_logs/2024-05-28T08_18_30_179Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-05-28T08_18_26_722Z-debug-0.log


Linux 6.1.0-10-amd64
node v18.19.0
npm  v9.2.0

**Comment by lightaffaire** [comment]
$ npm install -g mudslide

npm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node-18 /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/root/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 127
npm ERR! npm ERR! path /root/.npm/_cacache/tmp/git-cloneX1ibY1
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c tsc
npm ERR! npm ERR! sh: line 1: tsc: command not found
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-05-28T08_46_39_130Z-debug-0.log

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-05-28T08_46_37_519Z-debug-0.log

**Comment by robvanderleek** [comment]
Hi @lightaffaire @schleiche123 @chhajervikram 

Please check the newest release ([0.26.0](https://github.com/robvanderleek/mudslide/releases/tag/0.26.0)), hopefully this fixes your issues.

**Comment by schleiche123** [comment]
@robvanderleek 

It works. Thank you very much :)

**Comment by lightaffaire** [comment]
It works again. Thanks Rob!

**Comment by chhajervikram** [comment]
Thank You Sir It works .
