### ISSUE TITLE
mudslide keeps disconnecting from Whatsapp.

### ISSUE THREAD

**Issue by silvaalex2021** [robvanderleek/mudslide#94]
This problem of mine started some time ago and it’s getting worse.
I have been using Mudslide for two or three months, and recently, I have been losing the connection to WhatsApp more and more frequently. At the beginning of using the tool, the disconnection happened once a week or a little less. Then it started happening once a day, and now, it has gotten to the point where I have to reconnect several times a day!
In WhatsApp, Mudslide is not disconnected and continues to appear in the list of connected devices, but suddenly when I run "/usr/bin/npx mudslide@latest me", it shows me the QR code to reconnect.
Using "/usr/bin/npx mudslide@latest login" and scanning the QR code does not work to reestablish the connection, it only connects if I remove the cache folder or run "/usr/bin/npx mudslide@latest logout" and "/usr/bin/npx mudslide@latest login" and then scan the QR code.
Any idea what might be happening?

Just now, as I was reporting this issue, I got disconnected again, did the process mentioned above to reconnect, and got disconnected once more!

Any help will be greatly appreciated!

Thank you!

**Comment by robvanderleek** [comment]
Hi @silvaalex2021 

Sorry to hear Mudslide is not working for you.
Personally, I do not experience this problem, but I'll leave this issue open to check if other users experience the same behavior.

You might also want to check [the Issues of the Baileys repository](https://github.com/WhiskeySockets/Baileys/issues) (Mudslide is a wrapper around that library).
Please note that the library, or the API it's using, is not officially supported by WhatsApp. Based on your usage pattern you might get blocked (not sure if this is actually the case), can you share a bit about your usage pattern perhaps?

**Comment by Anayaali2019** [comment]
i am facing same issue while sending from webhook 
if i invoke mudslide login (it show your are logged in)it work fine for few days after that i goes to sleep again i have check webhook working fine ..

**Comment by WolfRamiO74** [comment]
same here, i log in, work for a day, then the app log out its self.

**Comment by WolfRamiO74** [comment]
Hello, i am facing the same issue... i did the login with the QR, mudslide work for one or two days, then the app lost the login and i have to read the QR again.

**Comment by robvanderleek** [comment]
Unfortunately I can't reproduce this issue.
For me, Mudslide keeps working without the need to re-authenticate periodically.

If you do have problems: It could be related to the amount of traffic you are generating. Please don't use this App for heavy automation as it's based on the unofficial WA API.
