### ISSUE TITLE
mudslide cannot send message

### ISSUE THREAD

**Issue by Goran53nja** [robvanderleek/mudslide#95]
Hi @robvanderleek  

 After a few successful messages mudslide stopped sending messages. I logged out and logged in several times, but without success. The device is visible in connected devices on Android.

How to find the cause of the problem ? 

Attached is a screenshot of the unsuccessful sending.
![Screenshot from 2024-06-19 10-11-08](https://github.com/robvanderleek/mudslide/assets/173244045/05d16545-29e5-417f-977d-78fd10ad75d7)

 Thank you !

 Best regards 

  Goran

**Comment by robvanderleek** [comment]
Hi @Goran53nja 

Sorry to hear, can you try again with the latest version? `npx mudslide@latest`

**Comment by Goran53nja** [comment]
Hi @robvanderleek 

Thank you. Same again.

![Screenshot from 2024-06-19 14-12-49](https://github.com/robvanderleek/mudslide/assets/173244045/b526771f-35ac-47b3-9fad-937867ec0e38)

OS Debian 12...
The installation was done according to this instruction....

 https://community.home-assistant.io/t/alternative-howto-for-using-whatsapp-notifications-sent-from-a-linux-host/674505

**Comment by robvanderleek** [comment]
Hi @Goran53nja 

I just tested the logout/login procedure and for me it still works with the latest version of Mudslide.
Perhaps you can test it from a different machine?

To be sure there's no stale cache data you can also manually clean the cache folder that's reported when you run `npx mudslide@latest me`
Also, you can run the send command with the `-vvv` flag, that will generate a lot of debug messages that could indicate where it goes wrong: `npx mudslide@latest -vvv send me 'Hello world'`

If the problem is related to the [Baileys library](https://github.com/WhiskeySockets/Baileys) that Mudslide is based upon, or related to your WA account, I'm afraid I can't help you any further.

**Comment by Goran53nja** [comment]
Hi @robvanderleek 



> I just tested the logout/login procedure and for me it still works with the latest version of Mudslide.

Login and logout works for me and the Android device sees an active connected device.  Different machine I can try later.

> To be sure there's no stale cache data you can also manually clean the cache folder that's reported when you run `npx mudslide@latest me`
> Also, you can run the send command with the `-vvv` flag, that will generate a lot of debug messages that could indicate where it goes wrong: `npx mudslide@latest -vvv send me 'Hello world'`

Here I copy the command output  there are no  any debug messages:

/ ___|   _| |__ (_) ___| |_ _ __ _   _  ___| | __
| |  | | | | '_ \| |/ _ \ __| '__| | | |/ __| |/ /
| |__| |_| | |_) | |  __/ |_| |  | |_| | (__|   < 
 \____\__,_|_.__/|_|\___|\__|_|   \__,_|\___|_|\_\
                                                  
Welcome to Armbian_community 24.8.0-trunk.164 Bookworm with Linux 6.6.31-current-sunxi

No end-user support: untested automated build

System load:   46%           	Up time:       2:31	Local users:   2            	
Memory usage:  4% of 1.93G  	IP:	       192.168.1.85
CPU temp:      37°C           	Usage of /:    12% of 15G    	

[ Menu-driven system configuration (beta): sudo apt update && sudo apt install armbian-config ]


host@cubietruck:~$ npx mudslide@latest -vvv send me 'A test text message from my linked account to my phone’
> ^C
host@cubietruck:~$ npx mudslide@latest -vvv send me 'A test text message from my linked account to my phone’
> ^C
host@cubietruck:~$ npx mudslide@latest login
ℹ  info      In the WhatsApp mobile app go to "Settings > Connected Devices > 
ℹ  info      Connect Device" and scan the QR code below
✔  success   Logged in
…  awaiting  Closing WA connection, waiting for 1 second(s)...
⭐ Please star Mudslide on GitHub! https://github.com/robvanderleek/mudslide
host@cubietruck:~$ npx mudslide@latest -vvv send me 'A test text message from my linked account to my phone’
> ^C
host@cubietruck:~$ ls
host@cubietruck:~$ ls -l -a
sveukupno 40
drwx------ 4 host host 4096 lip  18 10:29 .
drwxr-xr-x 3 root root 4096 lip  17 10:18 ..
-rw------- 1 host host 2442 lip  19 14:24 .bash_history
-rw-r--r-- 1 host host  220 lip  17 10:18 .bash_logout
-rw-r--r-- 1 host host 3601 lip  17 10:20 .bashrc
-rw------- 1 host host   20 lip  18 10:29 .lesshst
drwxr-xr-x 3 host host 4096 lip  17 11:03 .local
drwxr-xr-x 5 host host 4096 lip  17 10:33 .npm
-rw-r--r-- 1 host host  807 lip  17 10:18 .profile
-rw-r--r-- 1 host host    0 lip  17 10:26 .sudo_as_admin_successful
-rw-r--r-- 1 host host    0 lip  17 10:18 .Xauthority
-rw-r--r-- 1 root root   78 lip  17 10:20 .xsessionrc
host@cubietruck:~$ cd .npm/
host@cubietruck:~/.npm$ ls
_cacache  _logs  _npx  _update-notifier-last-checked
host@cubietruck:~/.npm$ cd _cacache/
host@cubietruck:~/.npm/_cacache$ ls
content-v2  index-v5  tmp
host@cubietruck:~/.npm/_cacache$ cd content-v2/
host@cubietruck:~/.npm/_cacache/content-v2$ ls
sha512
host@cubietruck:~/.npm/_cacache/content-v2$ cd sha512/
host@cubietruck:~/.npm/_cacache/content-v2/sha512$ ls
00  0b  13  1e  2b  35  3e  4e  58  64  6d  77  88  92  a0  ad  ba  c3  d0  dc  e6  f1  fd
01  0c  14  1f  2c  36  41  4f  59  65  6e  78  8a  93  a1  ae  bb  c5  d2  dd  e7  f2  fe
02  0d  15  20  2d  37  42  51  5b  67  6f  7b  8b  94  a3  af  bc  c6  d3  df  e8  f4  ff
03  0e  17  25  2e  38  43  52  5d  68  70  7d  8d  95  a4  b0  bd  c8  d4  e0  e9  f6
06  0f  19  26  31  39  45  53  5e  69  71  7e  8e  96  a5  b2  be  c9  d7  e1  ea  f7
08  10  1a  28  32  3a  48  54  5f  6a  74  82  8f  97  a6  b3  c0  ca  d8  e3  ed  f8
09  11  1b  29  33  3b  49  55  60  6b  75  84  90  9a  a7  b5  c1  cb  d9  e4  ef  f9
0a  12  1c  2a  34  3d  4b  56  63  6c  76  86  91  9d  ac  b7  c2  cf  da  e5  f0  fa
host@cubietruck:~/.npm/_cacache/content-v2/sha512$ cd ..
host@cubietruck:~/.npm/_cacache/content-v2$ cd ..
host@cubietruck:~/.npm/_cacache$ cd ..
host@cubietruck:~/.npm$ ls
_cacache  _logs  _npx  _update-notifier-last-checked
host@cubietruck:~/.npm$ cd _npx/
host@cubietruck:~/.npm/_npx$ ls
3d8e8e1f43a0b507  ce95761724e6020f
host@cubietruck:~/.npm/_npx$ cd 3d8e8e1f43a0b507/
host@cubietruck:~/.npm/_npx/3d8e8e1f43a0b507$ ls
node_modules  package.json  package-lock.json
host@cubietruck:~/.npm/_npx/3d8e8e1f43a0b507$ ls
node_modules  package.json  package-lock.json
host@cubietruck:~/.npm/_npx/3d8e8e1f43a0b507$ cd ..
host@cubietruck:~/.npm/_npx$ ls
3d8e8e1f43a0b507  ce95761724e6020f
host@cubietruck:~/.npm/_npx$ cd ..
host@cubietruck:~/.npm$ npx mudslide@latest logot
^C
host@cubietruck:~/.npm$ npx mudslide@latest logout
✔  success   Logged out
…  awaiting  Closing WA connection, waiting for 1 second(s)...
⭐ Please star Mudslide on GitHub! https://github.com/robvanderleek/mudslide
host@cubietruck:~/.npm$ cd .npm/
-bash: cd: .npm/: Nema takve datoteke ili direktorija
host@cubietruck:~/.npm$ ls
_cacache  _logs  _npx  _update-notifier-last-checked
host@cubietruck:~/.npm$ cd _cacache/
host@cubietruck:~/.npm/_cacache$ ls
content-v2  index-v5  tmp
host@cubietruck:~/.npm/_cacache$ rm -R *
host@cubietruck:~/.npm/_cacache$ cd ..
host@cubietruck:~/.npm$ npx mudslide@latest login
ℹ  info      In the WhatsApp mobile app go to "Settings > Connected Devices > 
ℹ  info      Connect Device" and scan the QR code below
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█
████ ▀█▄█▄ ▀▄  █ ▄▀█▀█ ▄  █▀   ▀▀█▄▄▄█ █▀▄  ▄▄▄▄█ ▄█▀██
██ ▄██ ▄ █▄▀▄▄▄▄▄▀▀▀ ███▄▄ █▀▀█▄▄▄██ ▄▄▀▄██▄██▄▀▀▀▄▄▄██
█  ▄▄ ▀▄▀▀▀▀█  █▀▄ ▄  ▀▀█  ▀██▀█▄▀▄█    ██ ▄██▀ ▄█▄▀▄██
███ █▀█▄ ██▄▄▄█ ▄█  █▀ ▀▀▀▀▄▄█  █▄▄█▀ ▀█▀ ▄▄▄  ▄ ▄▀█▄▄█
█

✔  success   Logged in
◼  pause     Wait until WhatsApp finishes connecting, then press any key to exit
…  awaiting  Closing WA connection, waiting for 1 second(s)...
⭐ Please star Mudslide on GitHub! https://github.com/robvanderleek/mudslide
host@cubietruck:~/.npm$ npx mudslide@latest -vvv send me 'A test text message from my linked account to my phone’
> ^C
host@cubietruck:~/.npm$ ls
_cacache  _logs  _npx  _update-notifier-last-checked
host@cubietruck:~/.npm$ cd _cacache/
host@cubietruck:~/.npm/_cacache$ ls
content-v2  index-v5  tmp
host@cubietruck:~/.npm/_cacache$ cd content-v2/
host@cubietruck:~/.npm/_cacache/content-v2$ ls
sha512
host@cubietruck:~/.npm/_cacache/content-v2$ 

it's possible a hardware problem, I'll see when I try another machine

**Comment by robvanderleek** [comment]
I also think it's best to first try it on a different machine.

Note that the cache folder from Mudslide is not inside the `.npm` folder. You can see what location Mudslide uses by running `npx mudslide@latest me`.
