### ISSUE TITLE
slow message sending by cmd

### ISSUE THREAD

**Issue by roleesoft** [robvanderleek/mudslide#98]
How to reduce the message sending time per cmd line, minimum time to send message is 5 seconds

**Comment by robvanderleek** [comment]
This program has explicit wait times to make sure messages are properly delivered and to not flood the WA API.

If you want to send messages faster, you can use the underlying [Baileys](https://github.com/WhiskeySockets/Baileys) library, but be aware that it is not an official supported library by WhatsApp so it could stop working without notice, or your account may be blocked.
